# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be331d9b149c866b86fec91c63bf0f231b36af2f768a24c2407b2ba632dd2a0c975aaa96d845e63547358cad148aa6bad9d383dd9092bb3a98483ffbf243fe2c

test:
  secret_key_base: ce51e4928226ae3ace722edd5bf264fd7df6b0f5e9f7bc2c0254bf465d74c257385189a813f8b1829a79506ce4f1351a39a568d3f18769b40daab43e3aaf95f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
